# Generated by Django 5.2.1 on 2025-06-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='character_name',
            field=models.CharField(default='おうるくん', max_length=7),
        ),
    ]
