# Generated by Django 5.2.1 on 2025-06-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_character_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='character_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='おうるくん', max_length=8),
        ),
    ]
