# Generated by Django 5.2 on 2025-05-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dialogue", "0002_rename_input_text_dialoguelog_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialoguelog",
            name="user_input",
            field=models.TextField(default="Default input"),
        ),
    ]
