# Generated by Django 5.2 on 2025-05-13 05:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dialogue", "0003_dialoguelog_user_input"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dialoguelog",
            name="user_input",
        ),
    ]
