# Generated by Django 5.2.1 on 2025-06-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0005_remove_dialoguelog_message_dialoguelog_response_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialoguelog',
            name='emotion',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
