# Generated by Django 5.2.1 on 2025-06-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0006_dialoguelog_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialoguelog',
            name='nickname',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
