# Generated by Django 5.2.1 on 2025-06-13 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0007_dialoguelog_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialoguelog',
            name='nickname',
        ),
    ]
