# Generated by Django 5.2.1 on 2025-06-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0008_remove_dialoguelog_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialoguelog',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
