# Generated by Django 5.2.1 on 2025-06-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0009_dialoguelog_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialoguelog',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='userdialogfeature',
            name='feature_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1),
        ),
    ]
