# Generated by Django 5.2.1 on 2025-06-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0010_remove_dialoguelog_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdialogfeature',
            name='subtype',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
