# Generated by Django 5.2.1 on 2025-06-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0011_userdialogfeature_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdialogfeature',
            name='subtype',
        ),
        migrations.AddField(
            model_name='userdialogfeature',
            name='entry_mode',
            field=models.CharField(choices=[('survey', 'Survey'), ('quick', 'Quick')], default='quick', max_length=10),
        ),
        migrations.AddField(
            model_name='userdialogfeature',
            name='personality',
            field=models.CharField(choices=[('talkative', 'Talkative'), ('calm', 'Calm'), ('neutral', 'Neutral')], default='neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdialogfeature',
            name='feature_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
        ),
    ]
